name: (Live) Deploy on the server
on:
  push:
    branches:
      - release
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-action@v1.0.3
      with:
        command_timeout: 30m
        host: ${{ secrets.LIVE_DEPLOY_HOST }}
        username: ${{ secrets.LIVE_USERNAME }}
        key: ${{ secrets.LIVE_DEPLOY_KEY }}
        script: ./deploy.sh
